### ISSUE TITLE
Modern Statistics: PMF vs PDF

### ISSUE THREAD

**Issue by SPDA36** [gedeck/mistat-code-solutions#43]
**Describe the problem**

Chapter 2, Page 55, section 2.2.1.1.  The bolded words after equation 2.13: "probability distribution function," shouldn't that be called "probability mass function"?

**Comment by gedeck** [comment]
The term _probability mass function_ applies to a discrete distribution and be more precise but _probability distribution function is_ widely accepted and applies to both continuous and discrete distributions. It is the term we use in the book.

**Comment by SPDA36** [comment]
Thanks for clearing that up.  I'm used to seeing PMF (since that section was for discrete distributions) and I'm sure others might be used to that term as well so this "issue" might serve as clarity for others.

**Comment by gedeck** [comment]
Added clarification to errata
