### ISSUE TITLE
Modern Statistics: statsmodels API for anova has changed

### ISSUE THREAD

**Issue by SPDA36** [gedeck/mistat-code-solutions#46]
**Describe the problem**
Error below when using mistat.stepwise_regression(outcome=y, all_vars=X, data=df3)

**Software Error**
File ~\mistat\regression\stepwiseRegression.py:19, in find_best_model_partialF(outcome, variable_sets, data, old_model, opt_max)
     17 with warnings.catch_warnings():
     18     warnings.simplefilter("ignore")
**--->** 19     comparison = **sms.anova**.anova_lm(old_model, new_model)
     20 if optF * partialF < optF * comparison.F[1]:
     21     best_vars = variables

**AttributeError: module 'statsmodels.stats' has no attribute 'anova'**

**Suggested change**
import statsmodels.api as sm
---> 19     comparison = **sm.stats.anova_lm**(old_model, new_model)

**Software (if the problem is with the code):**
OS: Windows
Release: 10
Python implementation: CPython
Python version       : 3.11.0
IPython version      : 8.12.0
statsmodels: 0.14.0

**Comment by gedeck** [comment]
Released as 0.1.12
