### ISSUE TITLE
Modern Statistics: Se clarification

### ISSUE THREAD

**Issue by SPDA36** [gedeck/mistat-code-solutions#48]
Chapter 4, page 251, states that `The square roots of these variances estimates are the "std err".... The Se value is shown in the regression summary output as Scale.`
Page 250 states that `Se^2 = 5.8869`
Page 248 in the results summary states that `Scale: 5.8832`
Suspect there is rounding error, but none-the-less, the sqrt of 5.8832 = 2.426.  Thus, `Se` =/= `Scale`

Problem: 
The `Scale` output cannot be both variance and standard error. 

https://www.statsmodels.org/dev/generated/statsmodels.regression.linear_model.OLSResults.scale.html
`Note that the square root of scale is often called the standard error of the regression.` 

Solution:
`The square roots of these variances estimates are the "std err".... The Se^2 value is shown in the regression summary output as Scale.`

**Comment by gedeck** [comment]
Thank you for your feedback. I'll add this to the errata page.
