### ISSUE TITLE
Modern Statistics: Proportional Sample Allocation Ch. 5 pg 317 Equation Clarification

### ISSUE THREAD

**Issue by SPDA36** [gedeck/mistat-code-solutions#50]
Proportional Sample Allocation Ch. 5 pg 317 Equation Clarification

The equation on page 317 in the top section under V$`_{\text{simple}}`$ ...

where
$`\tilde{\sigma}_N^2 = \frac{N}{N-1}\sigma_N^2`$

Should it read?:
$`\tilde{\sigma}_{N_i}^2 = \frac{N_i}{N_i-1}\sigma_{N_i}^2`$

I get the sense that it should because of how the equation for $\bar{\sigma}_N^2$ on page 318 is solved.

**Comment by SPDA36** [comment]
I think I might have read this section incorrectly and confused the `proportional` method with the `simple` method of finding the variance of the mean.  Please advise.

**Comment by gedeck** [comment]
The equations in the book are correct.
