### ISSUE TITLE
Modern Statistics: Ch. 6 pg. 334 code inconsistency.

### ISSUE THREAD

**Issue by SPDA36** [gedeck/mistat-code-solutions#51]
For model_3 object in the code block, `smf.ols()` function `formula` argument has the wrong formula object referenced.  Should read `formula` instead of `poly_formula` or vice versa.

Looking at the notebook at the following link: https://github.com/gedeck/mistat-code-solutions/blob/main/ModernStatistics/notebooks/Chap006.ipynb, it appears `poly_formula` is the selected object name. 

This is just a object labeling inconsistency issue in the textbook.

**Comment by gedeck** [comment]
This is interesting. We used `pweave` to write the book. This means that the code is embedded with the Latex. pweave then takes this, executes the code and combines it with the Latex to create a latex file. The latex files are then used to create the book. We also extract the Python code from these files and create the Jupyter notebooks. There should be no discrepancy like this between the book and the notebook. I assume that during the editing of the book, the publisher changed `poly_formula` to `formula` in the definition, but not in the `smf.ols` function call. 

We add this as an errata.

**Comment by SPDA36** [comment]
Dr. Gedeck, I'm a fan of your work and of course the other contributors as well.  I know I have been posting a lot of issues lately (all of which were minor or not an issue as I had some miss understandings).  Anyways, your book has been a refreshing read and your use of bootstrapping has help me understand a lot more of the concepts of statistics that my undergraduate degree glossed over.
